title: API documentation
description: Documenting the REST API as a part of a student project in the BTH course "vteam".

remote_theme: just-the-docs/just-the-docs

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme